### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by bandithedoge** [bandithedoge/zigplug#1]
### 0.1
- [ ] Implement all the most commonly used CLAP extensions
- [x] Process note events and add synthesizer examples
- [ ] Properly document the API and write more examples, possibly a short tutorial/article
- [ ] Build for and test on Windows and macOS
- [x] Make hard RT-capable plugins possible by removing mutexes
- [x] Properly sync main and audio threads
- [x] Parse features
- [x] Avoid global variables
- [x] Sample-accurate parameter automation
- [x] Proper state serialization
- [ ] Think of a better name

### 0.2?
- [ ] Actual GUI (https://github.com/ypsvlq/wio)
    - [ ] Create one or more separate GUI backend integration repos, DVUI is a good starting point
    - [ ] Expose sample data to GUI (for visualizing signals)
- More formats
	- [ ] VST3 and AU (can just be https://github.com/free-audio/clap-wrapper for now)
	- [ ] Standalone executables (contribute more audio backends to wio?)
	- [ ] LV2
	- [ ] VCV Rack?
- [ ] Collect potential 3rd-party projects that extend zigplug (eg. GUI backends) – awesome-zigplug?.
- [ ] Look into statically linking as much as possible
- [ ] Support real MIDI (not just `clap_event_note_t`)
- [ ] Faust integration example?
- [ ] Support multiple plugin descriptors in one binary
- [ ] 64-bit sample processing
- [ ] User-defined state (de-)serialization (not just parameters)
- [ ] Presets

### 1.0
- [ ] Wait for Zig to reach 1.0

**Comment by JohnCorby** [comment]
im doing dvui wio integration rn, and @PowerUser64 is working on plugging into a faust generated code. i imagine when we're done bashing our heads against those walls we'll have something you could use or build off of

**Comment by bandithedoge** [comment]
Thanks @JohnCorby, I'm excited to see what you come up with. Are you planning on making it public soon? I'd love to see if I can contribute a bit.

**Comment by PowerUser64** [comment]
It'll be public at some point, yeah! I think we'll probably wait until we're satisfied with what we've got until we release it though, so it might be a bit before we do. I can make a comment here when it's available if you'd like!

**Comment by bandithedoge** [comment]
@PowerUser64 Please do, I'm very interested!

**Comment by JanBeelte** [comment]
@bandithedoge +1 for DVUI integration :-)

**Comment by PowerUser64** [comment]
For the record (I already communicated this to @bandithedoge), my plugin is public now: https://github.com/PowerUser64/tonebender. It's not done yet, but this is where you can find it.

The faust code itself is not public since I want to wait until v1 to release it, but everything else is there.
